# Future Sales Prediction

#### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("advertising.csv")
data.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
data.isna().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [4]:
import plotly.express as px
import plotly.graph_objects as go

In [5]:
figure = px.scatter(data_frame = data,x = "Sales",y = "TV",size="TV",trendline="ols")
figure.show()

In [6]:
figure = px.scatter(data_frame = data,x = "Sales",y = "Radio",size="Radio",trendline="ols")
figure.show()

In [7]:
figure = px.scatter(data_frame = data,x = "Sales",y = "TV",size="Newspaper",trendline="ols")
figure.show()

In [8]:
correlation = data.corr()
correlation["Sales"].sort_values(ascending=False)

Sales        1.000000
TV           0.901208
Radio        0.349631
Newspaper    0.157960
Name: Sales, dtype: float64

In [10]:
x = np.array(data.drop(["Sales"],axis=1))
y = np.array(data["Sales"])

In [11]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [13]:
model.score(X_test,y_test)

0.9059011844150826

In [17]:
features = np.array([[230.1,37.8,69.2]])
print(model.predict(features))

[21.37254028]